### PR TITLE
Add Higher-Order DisCoCat notebook

### PR DESCRIPTION
**Pull request by toumix**

### CODE REVIEW

**Review by giodefelice — COMMENTED** [review]
just adding a notebook about Peirce-Lambek-Montague

**Comment by giodefelice** [comment]
Notebook for higher-order-discocat paper

**Comment by toumix** [comment]
@giodefelice you closed and didn't approve, not very nice of you... 😅

**Review by giodefelice — APPROVED** [review]
Notebook for higher-order paper

**Pull request merged**
