### PR TITLE
Bubbles with multiple args

### PR DESCRIPTION
**Pull request by toumix**

### CODE REVIEW

**Comment by toumix** [comment]
@y-richie-y and @RazinShaikh would be nice to get your review so I can rebase #280 onto this one, then we can have a third PR for drawing frames with slots stacked horizontally!

**Review by RazinShaikh — COMMENTED** [review]
For frames with multiple arguments, could you give an option to choose whether the arguments are stacked horizontally or vertically in the drawing?

**Comment by toumix** [comment]
Yep that's the plan for the next PR! Let's merge this one as an intermediate step though

**Comment by RazinShaikh** [comment]
Sounds good. The PR looks good to me but I don't really understand the drawing part of the code.

**Review by RazinShaikh — APPROVED** [review]

**Comment by toumix** [comment]
Yeah I would say there is not so much point diving into the drawing code given that the next PR will refactor anyway.

**Pull request merged**
